# -*- coding: utf-8 -*-
"""lab1cpp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19wHDvYCLES64yDib0ShJzJdebWz0HTR-
"""



import pandas as pd
import matplotlib.pyplot as plt

# Загрузка данных из Excel файла
df_1 = pd.read_excel('/Линейный_поиск_макс (1) (1).xlsx')

# Создание графика на основе данных из столбцов 'x' и 'y'
plt.plot(df_1['x'], df_1['y'])
plt.title('Линейный поиск (худший случай)')
plt.xlabel('Размер')
plt.ylabel('Время')
plt.grid(True)
plt.show()

df_2 = pd.read_excel('/бин_поиск_случ.xlsx')

# Создание графика на основе данных из столбцов 'x' и 'y'
plt.plot(df_2['x'], df_2['y'])
plt.title('Бинарное поиск (число из массива)')
plt.xlabel('Размер')
plt.ylabel('Время')
plt.grid(True)
plt.show()

df_3 = pd.read_excel('/Копия бин_поиск_макс.xlsx')

# Создание графика на основе данных из столбцов 'x' и 'y'
plt.plot(df_3['x'], df_3['y'])
plt.title('Бинарное поиск (худший случай)')
plt.xlabel('Размер')
plt.ylabel('Время')
plt.grid(True)
plt.show()

df_4 = pd.read_excel('/Копия линейный_поиск_средний.xlsx')

# Создание графика на основе данных из столбцов 'x' и 'y'
plt.plot(df_4['x'], df_4['y'])
plt.title('Линейный  поиск (худший случай)')
plt.xlabel('Размер')
plt.ylabel('Время')
plt.grid(True)
plt.show()